// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsjbbzrfvzxtymgolnqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzamJienJmdnp4dHltZ29sbnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzI5OTYsImV4cCI6MjA2MjkwODk5Nn0.td8c5PfCUG-gXJtpj3sqqPjL2PucKRIAKYfff1DnX3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);